-- Migration 013: Seed default values for company_eixos
-- Insere os eixos padrão. INSERT IGNORE evita erro se já existirem
-- (a UNIQUE KEY uniq_eixo_name garante a deduplicação).

INSERT IGNORE INTO company_eixos (id, name) VALUES
  (UUID(), 'Distribuidora'),
  (UUID(), 'Certificações'),
  (UUID(), 'Saúde'),
  (UUID(), 'Alimentação'),
  (UUID(), 'Facilities'),
  (UUID(), 'Materiais de Consumo'),
  (UUID(), 'Infraestrutura e Telecom'),
  (UUID(), 'Educação'),
  (UUID(), 'Artefatos'),
  (UUID(), 'Consultoria Especializada'),
  (UUID(), 'Tecnologia'),
  (UUID(), 'Construção e Engenharia'),
  (UUID(), 'Indústria e Automação'),
  (UUID(), 'Energia e Sustentabilidade'),
  (UUID(), 'Serviço de Locação'),
  (UUID(), 'Vestuário e Têxtil'),
  (UUID(), 'Transporte'),
  (UUID(), 'Gráfica'),
  (UUID(), 'Estruturas Metálicas'),
  (UUID(), 'Placa Solar'),
  (UUID(), 'Carregadores Elétricos'),
  (UUID(), 'Medicamentos'),
  (UUID(), 'Projetos'),
  (UUID(), 'Pães, Massas, Doces, Marmitas e Kit Lanches'),
  (UUID(), 'Serviço'),
  (UUID(), 'Óleos e Lubrificantes'),
  (UUID(), 'Prontuários Eletrônicos, Gestão de Frota, Epidemiologia, Mobilidade agente comunitário, auditoria hospitalar'),
  (UUID(), 'Atividade médica ambulatorial restrita a consultas'),
  (UUID(), 'Plano Odontológico'),
  (UUID(), 'Pavimentação'),
  (UUID(), 'Serviços recreativos, grafite'),
  (UUID(), 'Recapeamento de Pneus, Venda de Pneus novos, Câmaras e Rodas'),
  (UUID(), 'Nutracêuticos'),
  (UUID(), 'Serviços Advocatícios');
