-- Migration 015: Seed default values for company_segmentos
-- Insere os segmentos padrão. INSERT IGNORE evita erro se já existirem
-- (a UNIQUE KEY uniq_seg_name garante a deduplicação).

INSERT IGNORE INTO company_segmentos (id, name) VALUES
  (UUID(), 'Distribuidora de produtos e serviços'),
  (UUID(), 'Certificados Digitais'),
  (UUID(), 'Ação ambiental'),
  (UUID(), 'Artigos Cirúrgico-Hospitalar'),
  (UUID(), 'Alimentos Básicos'),
  (UUID(), 'Limpeza'),
  (UUID(), 'Educação'),
  (UUID(), 'Dedetizadora'),
  (UUID(), 'Serviços Médicos'),
  (UUID(), 'Café Gourmet'),
  (UUID(), 'Medicamento'),
  (UUID(), 'Telecomunicação'),
  (UUID(), 'Turismo'),
  (UUID(), 'Utensílios de Cozinha'),
  (UUID(), 'Caixa Papelão'),
  (UUID(), 'Equipamentos e Materiais Fisioterápicos'),
  (UUID(), 'Comportamento Humano'),
  (UUID(), 'Software'),
  (UUID(), 'Comunicação'),
  (UUID(), 'Materiais Hidráulicos'),
  (UUID(), 'Higiene Pessoal e Primeiros Socorros'),
  (UUID(), 'Eventos'),
  (UUID(), 'Serviços de Gestão de Saúde'),
  (UUID(), 'Alimentos Perecíveis'),
  (UUID(), 'Materiais Didáticos'),
  (UUID(), 'Direito'),
  (UUID(), 'Forno e Cozinha Profissional'),
  (UUID(), 'Energia Solar e Alternativa'),
  (UUID(), 'Acabamentos e Revestimentos'),
  (UUID(), 'Máquinas e Equipamentos'),
  (UUID(), 'Enxoval Hospitalar'),
  (UUID(), 'Veículos Leves'),
  (UUID(), 'Identificação Pessoal'),
  (UUID(), 'Máquinas e Equipamentos Cirúrgico-Hospitalar'),
  (UUID(), 'Mobiliário'),
  (UUID(), 'Estruturas Metálicas'),
  (UUID(), 'Carregador Veicular'),
  (UUID(), 'Refeições Coletivas'),
  (UUID(), 'Logística'),
  (UUID(), 'Placa Solar'),
  (UUID(), 'Carregadores Elétricos'),
  (UUID(), 'Medicamentos'),
  (UUID(), 'Projetos de Engenharia'),
  (UUID(), 'Alimentos'),
  (UUID(), 'Óleos e Lubrificantes'),
  (UUID(), 'Prontuários Eletrônicos, Gestão de Frota, Epidemiologia, Mobilidade agente comunitário, auditoria hospitalar'),
  (UUID(), 'Atividade médica ambulatorial restrita a consultas'),
  (UUID(), 'Plano Odontológico'),
  (UUID(), 'Pavimentação'),
  (UUID(), 'Grafite, Pinturas'),
  (UUID(), 'Recapeamento de Pneus, Venda de Pneus novos, Câmaras e Rodas'),
  (UUID(), 'Nutracêuticos'),
  (UUID(), 'Serviços Advocatícios');
