-- Migration 016: Seed default values for company_produtos
-- Insere os produtos padrão. INSERT IGNORE evita erro se já existirem
-- (a UNIQUE KEY uniq_prod_name garante a deduplicação).
-- Cada empresa pode selecionar múltiplos produtos via company_produto_links.

INSERT IGNORE INTO company_produtos (id, name) VALUES
  (UUID(), 'Diversos'),
  (UUID(), 'Certificado A1, A3'),
  (UUID(), 'Cirúrgico-Hospitalar'),
  (UUID(), 'Alho processado, ovos e grãos diversos'),
  (UUID(), 'Lavanderia e higienização têxtil'),
  (UUID(), 'Bonecos Simulação'),
  (UUID(), 'Produtos de Limpeza, Agua Sanitaria, Desinfetante, Sabonete Líquido, Hipoclorito'),
  (UUID(), 'Biomateriais'),
  (UUID(), 'Dedetização, descupinização, etc'),
  (UUID(), 'Diagnóstico'),
  (UUID(), 'Café Gourmet'),
  (UUID(), 'Cannabidiol'),
  (UUID(), 'Serviços e produtos SCM'),
  (UUID(), 'Intercâmbio Internacional'),
  (UUID(), 'Panela'),
  (UUID(), 'Papelão'),
  (UUID(), 'Cadeira de Rodas'),
  (UUID(), 'Bandeja INOX'),
  (UUID(), 'Treinamento Comportamental'),
  (UUID(), 'Antivírus'),
  (UUID(), 'Cateter'),
  (UUID(), 'Rádio Transmissores'),
  (UUID(), 'Exames Clínicos Oftalmológicos'),
  (UUID(), 'C-PVC e PVC-U'),
  (UUID(), 'Absorventes, Cotonetes, Algodão, Curativos Diversos, Lenço Umedecido e Fio Dental.'),
  (UUID(), 'Ingresso eletrônico via app'),
  (UUID(), 'Atendimento, Gestão Hospitalar'),
  (UUID(), 'Peixe'),
  (UUID(), 'Telemedicina'),
  (UUID(), 'Modelos Anatômicos'),
  (UUID(), 'Licenças'),
  (UUID(), 'Soluções de privacidade e proteção de dados'),
  (UUID(), 'Fornos Combinados'),
  (UUID(), 'Equipe multidisciplinar'),
  (UUID(), 'Painel Solar'),
  (UUID(), 'Construção e Reforma'),
  (UUID(), 'Máquinas de Café'),
  (UUID(), 'Uniformes Médicos, Camisolas'),
  (UUID(), 'Agência de Imprensa'),
  (UUID(), 'Aparelhos Médicos e Odontológicos'),
  (UUID(), 'Veículos à Combustão'),
  (UUID(), 'Produtos ortopédicos'),
  (UUID(), 'Robôs'),
  (UUID(), 'Crachá'),
  (UUID(), 'Equipamento Exames Clínicos / Cirúrgico Hospitalar'),
  (UUID(), 'Telefonia e Comunicação'),
  (UUID(), 'Grampeadores'),
  (UUID(), 'Colchão'),
  (UUID(), 'Estruturas Metálicas'),
  (UUID(), 'Carregador de Bateria / eletroposto, etc'),
  (UUID(), 'Eventos, Kit Lanches'),
  (UUID(), 'Transporte rodoviário'),
  (UUID(), 'Placa Solar'),
  (UUID(), 'Veículos Elétricos'),
  (UUID(), 'Injetáveis'),
  (UUID(), 'Blindagem e Blindados'),
  (UUID(), 'Carregadores Elétricos'),
  (UUID(), 'Medicamentos'),
  (UUID(), 'Projetos'),
  (UUID(), 'Pães, Massas, Doces, Marmitas e Kit Lanches'),
  (UUID(), 'Óleos e Lubrificantes'),
  (UUID(), 'Prontuários Eletrônicos, Gestão de Frota, Epidemiologia, Mobilidade agente comunitário, auditoria hospitalar'),
  (UUID(), 'Atividade médica ambulatorial restrita a consultas'),
  (UUID(), 'Plano Odontológico'),
  (UUID(), 'Pavimentação'),
  (UUID(), 'Grafite, Pinturas'),
  (UUID(), 'Venda de Pneus novos, Câmaras e Rodas'),
  (UUID(), 'Nutracêuticos'),
  (UUID(), 'Serviços Advocatícios');
